spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:person-api
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob.non-contextual-creation: true